const CAR = [
  {
    id: "1",
    brand: "BMW",
    model: "m3",
    year: 2012,
    fuel: "petrol",
    bodyType: "Sedan",
    price: 2500000,
    img: "./images/bmwm3.jpg",
  },
  {
    id: "2",
    brand: "Audi",
    model: "Rs6",
    year: 2014,
    fuel: "petrol",
    bodyType: "Estste",
    price: 4500000,
    img: "./images/audirs6.jpg",
  },
  {
    id: "3",
    brand: "Porsche",
    model: "Taycan",
    year: 2021,
    fuel: "electric",
    bodyType: "sedan",
    price: 12000000,
    img: "./images/porsche.jpg",
  },
  {
    id: "4",
    brand: "Land Rover",
    model: "Range Rover",
    year: 2020,
    fuel: "hybrid",
    bodyType: "SUV",
    price: 13300000,
    img: "./images/range.jpg",
  },
  {
    id: "5",
    brand: "KIA",
    model: "Carnival",
    year: 2021,
    fuel: "disel",
    bodyType: "MPV",
    price: 3600000,
    img: "./images/kia.jpg",
  },
  {
    id: "6",
    brand: "BMW",
    model: "i8",
    year: 2017,
    fuel: "hybrid",
    bodyType: "Cabrio",
    price: 4600000,
    img: "./images/bmwi8.jpg",
  },
  {
    id: "7",
    brand: "Ford",
    model: "F150",
    year: 2015,
    fuel: "disel",
    bodyType: "Pickup",
    price: 2700000,
    img: "./images/ford.jpg",
  },
  {
    id: "8",
    brand: "Volkswagen",
    model: "Golf",
    year: 2005,
    fuel: "petrol",
    bodyType: "Hatchback",
    price: 490000,
    img: "./images/golf.jpg",
  },
  {
    id: "9",
    brand: "Aston Martin",
    model: "Rapide",
    year: 2011,
    fuel: "petrol",
    bodyType: "sedan",
    price: 7700000,
    img: "./images/aston.jpg",
  },
];

export default CAR;
